ARG CUDA_VERSION


FROM nvcr.io/nvidia/deepstream:6.3-triton-multiarch

RUN apt-get update


RUN mkdir -p /opt/nvidia/deepstream/deepstream-6.3/sources/apps/deepstream_python_apps && git clone https://github.com/NVIDIA-AI-IOT/deepstream_python_apps.git /opt/nvidia/deepstream/deepstream-6.3/sources/apps/deepstream_python_apps
ADD user_additional_install_runtime.sh /

RUN chmod +x /user_additional_install_runtime.sh && /user_additional_install_runtime.sh



# Install Python 3.9
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update
# RUN apt-get install python3.9 python3-pip -y
RUN apt-get install libgl1-mesa-glx libglib2.0-0 git wget tzdata -y

ADD requirements_yolov5.txt /
RUN pip3 install -r requirements_yolov5.txt



 
